kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stakater-tekton-builder
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
      - pipelineresources
    verbs:
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stakater-tekton-builder
secrets:
  - name: stakater-git-auth
  - name: stakater-registry-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stakater-tekton-builder-binding
subjects:
  - kind: ServiceAccount
    name: stakater-tekton-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stakater-tekton-builder