apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: echo-status
spec:
  steps:
    - name: build-simple
      image: docker.io/library/busybox
      command:
        - /bin/sh
      args:
        - -c
        - "echo Running pipeline"